huggingface_config:
  character: '0'  # 希望生成声音的角色
  audio_speed: '1'  # 播放速度,可为保留一位小数点的小数[0.1 - 5]
  download_url: 'https://yeluo0204-sagirivits.hf.space/file='  # 填入刚复制以https开头的链接
  websocket: 'wss://yeluo0204-sagirivits.hf.space/queue/join'  # 填入以wss开头的websocket链接
  limitLength: 145  # 设置语音文字限长 0为无限制（注意这里是整数而不是字符串）

oss_config:
  access_key_id: 'LTAI5tHpk3jVk2LPRtxgfb6G'  # 阿里云 Access Key ID
  access_key_secret: 'FDpKIXmSgVVYB76k1nVRV2ZxVLXiOY'  # 阿里云 Access Key Secret
  endpoint: 'http://oss-cn-shenzhen.aliyuncs.com'  # OSS Endpoint
  bucket_name: 'yunchenqwq'  # Bucket 名称